name: pages

on:
  push:
    branches:
      - main

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build Slidev
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2
          workdir: ./ci
          cmds: |
            project init
            project update
            do build
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
